import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import process from 'node:process';
const root=process.cwd(); const contract=path.join(root,'contracts','TwinCharter.py');
const expected='f89e31328942900ff2d98c93e8835e55e45280f639d19eb9f77dacc33dfc32fc';
const sha=crypto.createHash('sha256').update(fs.readFileSync(contract)).digest('hex');
if(sha!==expected) throw new Error(`Contract SHA mismatch: ${sha}`);
const config=fs.readFileSync(path.join(root,'src','config.ts'),'utf8');
for(const token of ['0x7827A4a5dAC1414622944f328962A7E2Ef82a341','0xf1E7D355FBB76b8077879022510D66Ce5782D909',expected]) if(!config.includes(token)) throw new Error(`Missing config token ${token}`);
const bannedTerms=[['Clau','de'],['Chat','GPT'],['Open','AI'],['Anthro','pic'],['internal ','review'],['review ','request'],['predeploy ','review'],['AI ','feedback'],['generated by ','AI']].map(parts=>new RegExp(parts.join(''),'i'));

const skip=new Set(['node_modules','dist','.git']);
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(skip.has(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(/\.(md|ts|tsx|js|mjs|json|css|html|py|svg|txt)$/i.test(e.name)){const t=fs.readFileSync(p,'utf8');for(const r of bannedTerms)if(r.test(t))throw new Error(`Public hygiene hit ${r} in ${path.relative(root,p)}`)}}}
walk(root);
console.log('TwinCharter project verification PASS');
console.log(`Contract SHA256: ${sha}`);
console.log('Project address: 0x7827A4a5dAC1414622944f328962A7E2Ef82a341');
console.log('Runtime evidence: 0xf1E7D355FBB76b8077879022510D66Ce5782D909');
